# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-01 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sdwan', '0003_auto_20190301_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel_Router_pingresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(max_length=60, unique=True)),
                ('mgtIP', models.CharField(max_length=60)),
                ('success', models.CharField(max_length=60)),
                ('destinationIP', models.CharField(max_length=60)),
                ('packet_loss', models.CharField(max_length=60)),
                ('rtt_min', models.CharField(max_length=60)),
                ('rtt_avg', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
            ],
        ),
    ]
