# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sdwan', '0004_classmodel_router_pingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel_router_pingresult',
            name='password',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classmodel_router_pingresult',
            name='username',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classmodel_router_pingresult',
            name='router_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='classmodel_router_pingresult',
            name='time',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
