# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-02 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sdwan', '0005_auto_20190301_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel_Router_Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interface_id', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('last_link_down_time', models.CharField(max_length=60)),
                ('last_link_up_time', models.CharField(max_length=60)),
                ('rx_byte', models.CharField(max_length=60)),
                ('tx_byte', models.CharField(max_length=60)),
                ('running', models.CharField(max_length=60)),
                ('disabled', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
            ],
        ),
    ]
