# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-02 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sdwan', '0007_auto_20190302_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel_router_interface',
            name='interface_id',
            field=models.CharField(max_length=60),
        ),
    ]
